
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Enriquie
 */
public class MAIN extends javax.swing.JFrame {
    
    private ArrayList<String> arrayList = new ArrayList<>();
    private LinkedList<String> linkedList = new LinkedList<>();
    private Sequence<String> sequence = new Sequence<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MAIN.class.getName());

    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        ADD2ARY_BTN = new javax.swing.JButton();
        ADD2Lnk_BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        SHOWARY_BTN = new javax.swing.JButton();
        SHOWLNK_BTN = new javax.swing.JButton();
        SHOWSEQ_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("DATA STRUCTURE LABORATORY 6 - GROUP 1");

        jLabel2.setText("Input text or number :");

        ADD2ARY_BTN.setText("Add to Array List");
        ADD2ARY_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD2ARY_BTNActionPerformed(evt);
            }
        });

        ADD2Lnk_BTN.setText("Add to Linked List");
        ADD2Lnk_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD2Lnk_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ADD2ARY_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ADD2Lnk_BTN)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADD2ARY_BTN)
                    .addComponent(ADD2Lnk_BTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SHOWARY_BTN.setText("Show Array List");
        SHOWARY_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWARY_BTNActionPerformed(evt);
            }
        });

        SHOWLNK_BTN.setText("Show Linked List");
        SHOWLNK_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWLNK_BTNActionPerformed(evt);
            }
        });

        SHOWSEQ_BTN.setText("Show Sequence");
        SHOWSEQ_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWSEQ_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(SHOWARY_BTN)
                .addGap(18, 18, 18)
                .addComponent(SHOWLNK_BTN)
                .addGap(18, 18, 18)
                .addComponent(SHOWSEQ_BTN)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SHOWARY_BTN, SHOWLNK_BTN, SHOWSEQ_BTN});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SHOWSEQ_BTN)
                    .addComponent(SHOWLNK_BTN)
                    .addComponent(SHOWARY_BTN))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADD2ARY_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD2ARY_BTNActionPerformed
        String input = TF1.getText().trim();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a value!");
            return;
        }
        arrayList.add(input);
        jTextArea1.append("Added to ArrayList: " + input + "\n");
        TF1.setText("");
    }//GEN-LAST:event_ADD2ARY_BTNActionPerformed

    private void ADD2Lnk_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD2Lnk_BTNActionPerformed
        String input = TF1.getText().trim();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a value!");
            return;
        }
        linkedList.add(input);
        sequence.add(input); // Also add to custom Sequence
        jTextArea1.append("Added to LinkedList and Sequence: " + input + "\n");
        TF1.setText("");
    }//GEN-LAST:event_ADD2Lnk_BTNActionPerformed

    private void SHOWARY_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWARY_BTNActionPerformed
        StringBuilder sb = new StringBuilder("ArrayList Elements:\n");
        for (int i = 0; i < arrayList.size(); i++) {
            sb.append(i).append(": ").append(arrayList.get(i)).append("\n");
        }
        jTextArea1.setText(sb.toString());
    }//GEN-LAST:event_SHOWARY_BTNActionPerformed

    private void SHOWLNK_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWLNK_BTNActionPerformed
        StringBuilder sb = new StringBuilder("LinkedList Elements:\n");
        for (String s : linkedList) {
            sb.append(s).append("\n");
        }
        jTextArea1.setText(sb.toString());
    }//GEN-LAST:event_SHOWLNK_BTNActionPerformed

    private void SHOWSEQ_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWSEQ_BTNActionPerformed
        StringBuilder sb = new StringBuilder("Custom Sequence Elements:\n");
        Sequence<String>.SeqIterator it = sequence.iterator();
        while (it.hasNext()) {
            sb.append(it.next()).append("\n");
        }
        jTextArea1.setText(sb.toString());
    }//GEN-LAST:event_SHOWSEQ_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MAIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD2ARY_BTN;
    private javax.swing.JButton ADD2Lnk_BTN;
    private javax.swing.JButton SHOWARY_BTN;
    private javax.swing.JButton SHOWLNK_BTN;
    private javax.swing.JButton SHOWSEQ_BTN;
    private javax.swing.JTextField TF1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    class Sequence<T> {
        private ArrayList<T> items = new ArrayList<>();

        public void add(T element) {
            items.add(element);
        }

        public T get(int index) {
            return items.get(index);
        }

        public SeqIterator iterator() {
            return new SeqIterator();
        }

        class SeqIterator {
            private int index = 0;

            public boolean hasNext() {
                return index < items.size();
            }

            public T next() {
                return items.get(index++);
            }
        }
    }

}
