/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Enriquie
 */
public class Launcher extends javax.swing.JPanel {

    /**
     * Creates new form Launcher
     */
    public Launcher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1_LAUNCH = new javax.swing.JButton();
        jButton3_EXIT = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("v1.0"));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam11.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enrollment System");

        jButton1_LAUNCH.setText("LAUNCH");
        jButton1_LAUNCH.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1_LAUNCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LAUNCHActionPerformed(evt);
            }
        });

        jButton3_EXIT.setText("EXIT");
        jButton3_EXIT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1_LAUNCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3_EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1_LAUNCH)
                .addGap(21, 21, 21)
                .addComponent(jButton3_EXIT)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_LAUNCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LAUNCHActionPerformed
        javax.swing.JFrame frame = new javax.swing.JFrame("Enrollment System");
    frame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    frame.setContentPane(new EnrollmentSystem());
    frame.pack();
    frame.setLocationRelativeTo(null); // center on screen
    frame.setVisible(true);
    }//GEN-LAST:event_jButton1_LAUNCHActionPerformed

    private void jButton3_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_EXITActionPerformed
         try {
            FileHandler.saveToFile(RECORDS.RECORDS, "Records.dat");
            System.out.println("Saved Successfully to Workers.dat");
        } 
        catch (Exception e) {
            System.out.println("Error Saving from Workers.dat");
        }
        System.exit(0);
    }//GEN-LAST:event_jButton3_EXITActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_LAUNCH;
    private javax.swing.JButton jButton3_EXIT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

public static void main(String[] args) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            // Create a frame (window)
            javax.swing.JFrame frame = new javax.swing.JFrame("Launcher");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

            // Add the Launcher panel inside the frame
            frame.setContentPane(new Launcher());

            // Adjust window size and make visible
            frame.pack();
            frame.setLocationRelativeTo(null); // center on screen
            frame.setVisible(true);
        }
    });
}

    
}


