/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labrador_thirdexamination;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enriquie
 */
public class CHECKOUT extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CHECKOUT.class.getName());

    /**
     * Creates new form CHECKOUT
     */
    public CHECKOUT() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chk_table = new javax.swing.JTable();
        chkbtn_print = new javax.swing.JButton();
        chktf_PRICE = new javax.swing.JTextField();
        chktf_VAT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chk_change = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labrador_thirdexamination/exam11.png"))); // NOI18N

        chk_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "NAME", "PRICE", "QUANTITY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chk_table.setGridColor(new java.awt.Color(0, 0, 0));
        chk_table.setShowGrid(true);
        chk_table.setShowHorizontalLines(true);
        chk_table.setShowVerticalLines(true);
        chk_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(chk_table);
        if (chk_table.getColumnModel().getColumnCount() > 0) {
            chk_table.getColumnModel().getColumn(0).setResizable(false);
            chk_table.getColumnModel().getColumn(1).setResizable(false);
            chk_table.getColumnModel().getColumn(2).setResizable(false);
        }

        chkbtn_print.setText("PRINT RECEIPT");
        chkbtn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbtn_printActionPerformed(evt);
            }
        });

        chktf_PRICE.setText("0000000");
        chktf_PRICE.setMaximumSize(new java.awt.Dimension(64, 22));
        chktf_PRICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chktf_PRICEActionPerformed(evt);
            }
        });

        chktf_VAT.setText("%%%%");
        chktf_VAT.setMaximumSize(new java.awt.Dimension(64, 22));
        chktf_VAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chktf_VATActionPerformed(evt);
            }
        });

        jLabel2.setText("TOTAL in Pesos :");

        jLabel3.setText("VAT :");

        chk_change.setMaximumSize(new java.awt.Dimension(64, 22));

        jLabel4.setText("CHANGE :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chktf_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chktf_VAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkbtn_print)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chktf_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chktf_VAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkbtn_print)
                    .addComponent(chk_change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
    }//GEN-LAST:event_formWindowOpened

    private void chktf_PRICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chktf_PRICEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chktf_PRICEActionPerformed

    private void chktf_VATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chktf_VATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chktf_VATActionPerformed

    private void chkbtn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbtn_printActionPerformed
        SALES m = new SALES();
    m.setLocationRelativeTo(null); // center the window
    m.setVisible(true);
    }//GEN-LAST:event_chkbtn_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CHECKOUT().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField chk_change;
    private javax.swing.JTable chk_table;
    private javax.swing.JButton chkbtn_print;
    public javax.swing.JTextField chktf_PRICE;
    private javax.swing.JTextField chktf_VAT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void loadRecordsToTable() {
        try {

        SALESinv.SALESinvRECORDS = SALESFILEHANDLER.loadFromFile("SALESinvRECORDS.dat");

        DefaultTableModel model = (DefaultTableModel) chk_table.getModel();
        model.setRowCount(0);

        for (SALESinv r : SALESinv.SALESinvRECORDS) {
            model.addRow(new Object[]{
                r.getNAME(),
                r.getPRICE(),
                r.getQUANTITY()
            });
        }
        

        System.out.println("Records loaded successfully from Records.dat");
        calculateTotalPrice();

        } catch (Exception e) {
        System.out.println("Error loading records: " + e.getMessage());
        }
    }
    
    private void calculateTotalPrice() {
    DefaultTableModel model = (DefaultTableModel) chk_table.getModel();
    double total = 0.0;

    for (int i = 0; i < model.getRowCount(); i++) {
        Object qtyObj = model.getValueAt(i, 1);
        Object priceObj = model.getValueAt(i, 2);

        if (qtyObj != null && priceObj != null) {
            try {
                int qty = Integer.parseInt(qtyObj.toString());
                double price = Double.parseDouble(priceObj.toString());
                total += qty * price;
            } catch (NumberFormatException e) {
                System.out.println("Invalid number format in row " + i);
            }
        }
    }

    chktf_PRICE.setText(String.format("%.2f", total));
}
    
    
    public void setCheckoutData(DefaultTableModel salesModel) {
    DefaultTableModel model = (DefaultTableModel) chk_table.getModel();
    model.setRowCount(0);

    for (int i = 0; i < salesModel.getRowCount(); i++) {
        Object name = salesModel.getValueAt(i, 0);
        Object qty = salesModel.getValueAt(i, 1);
        Object price = salesModel.getValueAt(i, 2);
        model.addRow(new Object[]{name, qty, price});
    }

    calculateTotalPrice();
}
}
