/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labrador_thirdexamination;

/**
 *
 * @author Enriquie
 */
public class Launcher extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Launcher.class.getName());

    /**
     * Creates new form Launcher
     */
    public Launcher() {
        initComponents();
        
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            int x = (screenSize.width - getWidth()) / 2;
            int y = screenSize.height - getHeight() - 200;

            setLocation(x, y);
        
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.time.LocalDate today = java.time.LocalDate.now();
            java.time.LocalTime now = java.time.LocalTime.now();

            launcher_date.setText(today.format(java.time.format.DateTimeFormatter.ofPattern("MMMM dd, yyyy")));
            launcher_time.setText(now.format(java.time.format.DateTimeFormatter.ofPattern("hh:mm:ss a")));
            });
        timer.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        launch_launch = new javax.swing.JButton();
        launcher_exit = new javax.swing.JButton();
        launcher_time = new javax.swing.JLabel();
        launcher_date = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eCommerce v1.0");
        setBackground(new java.awt.Color(0, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(263, 566));
        setMinimumSize(new java.awt.Dimension(263, 566));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Launcher"));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labrador_thirdexamination/exam11.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setText("Store Management");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setText("System");

        launch_launch.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        launch_launch.setText("LAUNCH");
        launch_launch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        launch_launch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launch_launchActionPerformed(evt);
            }
        });

        launcher_exit.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        launcher_exit.setText("EXIT");
        launcher_exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        launcher_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launcher_exitActionPerformed(evt);
            }
        });

        launcher_time.setText("TIME 00:00:00");

        launcher_date.setText("DATE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(launch_launch)
                            .addComponent(launcher_exit)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(launcher_time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(launcher_date)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(launcher_time)
                    .addComponent(launcher_date))
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(launch_launch)
                .addGap(18, 18, 18)
                .addComponent(launcher_exit)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launch_launchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launch_launchActionPerformed
        manager m = new manager();
    m.setLocationRelativeTo(null);
    m.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_launch_launchActionPerformed

    private void launcher_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launcher_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_launcher_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      

        java.awt.EventQueue.invokeLater(() -> new Launcher().setVisible(true));

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton launch_launch;
    private javax.swing.JLabel launcher_date;
    private javax.swing.JButton launcher_exit;
    private javax.swing.JLabel launcher_time;
    // End of variables declaration//GEN-END:variables
}
