/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labrador_thirdexamination;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enriquie
 */
public class manager extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(manager.class.getName());


    /**
     * Creates new form manager
     */
    public manager() {
        initComponents();
        
        im_table.setAutoCreateRowSorter(true);
        
        
         javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.time.LocalDate today = java.time.LocalDate.now();
            java.time.LocalTime now = java.time.LocalTime.now();

            im_date.setText(today.format(java.time.format.DateTimeFormatter.ofPattern("MMMM dd, yyyy")));
            im_time.setText(now.format(java.time.format.DateTimeFormatter.ofPattern("hh:mm:ss a")));
            });
        timer.start();
        
        im_table.addMouseListener(new java.awt.event.MouseAdapter(){
        public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = im_table.getSelectedRow();
                im_name.setText(RECORDS.RECORDS.get(row).getNAME());
                im_info.setText(RECORDS.RECORDS.get(row).getINFO());
                im_mfg.setText(RECORDS.RECORDS.get(row).getMFG_DATE());
                im_exp.setText(RECORDS.RECORDS.get(row).getEXP_DATE());
                im_price.setText(String.format("%.2f", RECORDS.RECORDS.get(row).getPRICE()));
                im_qty.setText(String.valueOf(RECORDS.RECORDS.get(row).getQUANTITY()));
                }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        im_qty = new javax.swing.JTextField();
        im_price = new javax.swing.JTextField();
        im_exp = new javax.swing.JTextField();
        im_mfg = new javax.swing.JTextField();
        im_info = new javax.swing.JTextField();
        im_name = new javax.swing.JTextField();
        im_add = new javax.swing.JButton();
        im_update = new javax.swing.JButton();
        im_refresh = new javax.swing.JButton();
        im_save = new javax.swing.JButton();
        im_time = new javax.swing.JLabel();
        im_date = new javax.swing.JLabel();
        im_btnsales = new javax.swing.JButton();
        im_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        im_table = new javax.swing.JTable();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eCommerce v1.0");
        setBackground(new java.awt.Color(255, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Inventory Manager"));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("NAME :");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("INFO :");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("MFG DATE :");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("EXP DATE :");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("PRICE :");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("QUANTITY :");

        im_qty.setBackground(new java.awt.Color(255, 255, 204));

        im_price.setBackground(new java.awt.Color(255, 255, 204));

        im_exp.setBackground(new java.awt.Color(255, 255, 204));
        im_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_expActionPerformed(evt);
            }
        });

        im_mfg.setBackground(new java.awt.Color(255, 255, 204));

        im_info.setBackground(new java.awt.Color(255, 255, 204));

        im_name.setBackground(new java.awt.Color(255, 255, 204));

        im_add.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        im_add.setText("ADD");
        im_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_addActionPerformed(evt);
            }
        });

        im_update.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        im_update.setText("UPDATE");
        im_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_updateActionPerformed(evt);
            }
        });

        im_refresh.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        im_refresh.setText("REFRESH");
        im_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_refreshActionPerformed(evt);
            }
        });

        im_save.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        im_save.setText("SAVE");
        im_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_saveActionPerformed(evt);
            }
        });

        im_time.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        im_time.setText("TIME 00:00:00");

        im_date.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        im_date.setText("DATE");

        im_btnsales.setBackground(new java.awt.Color(0, 102, 51));
        im_btnsales.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        im_btnsales.setForeground(new java.awt.Color(255, 255, 204));
        im_btnsales.setText("$ GO TO SALES");
        im_btnsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_btnsalesActionPerformed(evt);
            }
        });

        im_delete.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        im_delete.setText("DELETE");
        im_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(im_info)
                            .addComponent(im_name)
                            .addComponent(im_price)
                            .addComponent(im_mfg)
                            .addComponent(im_qty)
                            .addComponent(im_exp)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(im_add)
                            .addComponent(im_save))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(im_refresh)
                                .addGap(18, 18, 18)
                                .addComponent(im_time)
                                .addGap(18, 18, 18)
                                .addComponent(im_date)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(im_update)
                                .addGap(18, 18, 18)
                                .addComponent(im_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                                .addComponent(im_btnsales, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {im_add, im_refresh, im_save, im_update});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(im_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(im_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(im_mfg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(im_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(im_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(im_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(im_add)
                        .addComponent(im_update)
                        .addComponent(im_delete))
                    .addComponent(im_btnsales, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(im_refresh)
                    .addComponent(im_save)
                    .addComponent(im_time)
                    .addComponent(im_date))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        im_table.setBackground(new java.awt.Color(255, 255, 204));
        im_table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        im_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        im_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "DESCRIPTION", "MFG DATE", "EXP DATE", "PRICE", "QUANTITY", "SOLD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        im_table.setGridColor(new java.awt.Color(0, 0, 0));
        im_table.setShowGrid(true);
        im_table.setShowHorizontalLines(true);
        im_table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(im_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Inventory Manager v1.0");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void im_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_im_expActionPerformed

    private void im_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_addActionPerformed
        try {
            String NAME = im_name.getText();
            String INFO = im_info.getText();
            String MFG_DATE = im_mfg.getText();
            String EXP_DATE = im_exp.getText();
            Double PRICE = Double.parseDouble(im_price.getText());
            int QUANTITY = Integer.parseInt(im_qty.getText());
            
            RECORDS.RECORDS.add(new RECORDS(NAME, INFO, MFG_DATE, EXP_DATE, PRICE, QUANTITY));
            DefaultTableModel model = (DefaultTableModel)im_table.getModel();
            model.addRow(new Object[]{NAME, INFO, MFG_DATE, EXP_DATE, PRICE, QUANTITY});  
            clearSelections();
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please Fill all Fields with proper values");
        }
    }//GEN-LAST:event_im_addActionPerformed

    private void im_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_saveActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Data saved Succesfully!");
        try {
            FileHandler.saveToFile(RECORDS.RECORDS, "RECORDS.dat");
            System.out.println("DATA UPDATED.");
        } 
        catch (Exception e) {
            System.out.println("Error Saving from Workers.dat");
        }
    }//GEN-LAST:event_im_saveActionPerformed

    private void im_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_refreshActionPerformed
        loadRecordsToTable();
        javax.swing.JOptionPane.showMessageDialog(this, "Data loaded succesfully!");
    }//GEN-LAST:event_im_refreshActionPerformed

    private void im_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_deleteActionPerformed
         
            int row  = im_table.getSelectedRow();
            if(row<0){
                JOptionPane.showMessageDialog(this, "Row deleted.");
                return;
            }
        RECORDS.RECORDS.remove(row);
        DefaultTableModel model = (DefaultTableModel)im_table.getModel();
        model.removeRow(row); 
    }//GEN-LAST:event_im_deleteActionPerformed

    private void im_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_updateActionPerformed
        try {
            int row = im_table.getSelectedRow();
            if(row<0){
                JOptionPane.showMessageDialog(this, "Please select a row to update");
                return;
            }
            String NAME = im_name.getText();
            String DESCRIPTION = im_info.getText();
            String MFG_DATE = im_mfg.getText();
            String EXP_DATE = im_exp.getText();
             Double PRICE = Double.parseDouble(im_price.getText());
            int QUANTITY = Integer.parseInt(im_qty.getText());
            
            RECORDS updated = new RECORDS(NAME, DESCRIPTION, MFG_DATE, EXP_DATE, PRICE, QUANTITY);
            RECORDS.RECORDS.set(row, updated);
            
            DefaultTableModel model = (DefaultTableModel) im_table.getModel();
            model.setValueAt(NAME, row, 0);
            model.setValueAt(DESCRIPTION, row, 1);
            model.setValueAt(MFG_DATE, row, 2);
            model.setValueAt(EXP_DATE, row, 3);
            model.setValueAt(PRICE, row, 4);
            model.setValueAt(QUANTITY, row, 5);
            
            clearSelections();
            
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please Fill all Fields with proper values");
        }
    }//GEN-LAST:event_im_updateActionPerformed

    private void im_btnsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_btnsalesActionPerformed
        SALES m = new SALES();
    m.setLocationRelativeTo(null); // center the window
    m.setVisible(true);
    FileHandler.saveToFile(RECORDS.RECORDS, "RECORDS.dat");
    loadRecordsToTable();
    this.dispose(); 
    }//GEN-LAST:event_im_btnsalesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadRecordsToTable();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new manager().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton im_add;
    private javax.swing.JButton im_btnsales;
    private javax.swing.JLabel im_date;
    private javax.swing.JButton im_delete;
    private javax.swing.JTextField im_exp;
    private javax.swing.JTextField im_info;
    private javax.swing.JTextField im_mfg;
    private javax.swing.JTextField im_name;
    private javax.swing.JTextField im_price;
    private javax.swing.JTextField im_qty;
    private javax.swing.JButton im_refresh;
    private javax.swing.JButton im_save;
    private javax.swing.JTable im_table;
    private javax.swing.JLabel im_time;
    private javax.swing.JButton im_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void clearSelections() {
            im_name.setText("");
            im_info.setText("");
            im_mfg.setText("");
            im_exp.setText("");
            im_price.setText("");
            im_qty.setText("");
    }

    private void loadRecordsToTable() {
        try {

        RECORDS.RECORDS = FileHandler.loadFromFile("Records.dat");

        DefaultTableModel model = (DefaultTableModel) im_table.getModel();
        model.setRowCount(0);

        for (RECORDS r : RECORDS.RECORDS) {
            model.addRow(new Object[]{
                r.getNAME(),
                r.getINFO(),
                r.getMFG_DATE(),
                r.getEXP_DATE(),
                r.getPRICE(),
                r.getQUANTITY()
            });
        }

        System.out.println("Records loaded successfully from Records.dat");

        } catch (Exception e) {
        System.out.println("Error loading records: " + e.getMessage());
        }
        
    }
}
