/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labrador_thirdexamination;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static labrador_thirdexamination.SALESinv.SALESinvRECORDS;



public class SALES extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SALES.class.getName());

    /**
     * Creates new form SALES
     */
    public SALES() {
        initComponents();
        
         sales_invtable.addMouseListener(new java.awt.event.MouseAdapter(){
        public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = sales_invtable.getSelectedRow();
                salestf_name.setText(RECORDS.RECORDS.get(row).getNAME());
                salestf_mfg.setText(RECORDS.RECORDS.get(row).getINFO());
                salestf_exp.setText(RECORDS.RECORDS.get(row).getMFG_DATE());
                salestf_price.setText(String.format("%.2f", RECORDS.RECORDS.get(row).getPRICE()));
                }
        });
         
         sales_chktable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = sales_chktable.getSelectedRow();
                if (selectedRow >= 0) {
                    Object qtyObj = sales_chktable.getValueAt(selectedRow, 1);
                    if (qtyObj != null) {
                        salestf_qty.setText(qtyObj.toString());
                    }
                }
            }
        });
         
        
        sales_invtable.setAutoCreateRowSorter(true);
        sales_chktable.setAutoCreateRowSorter(true);
        
         javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.time.LocalDate today = java.time.LocalDate.now();
            java.time.LocalTime now = java.time.LocalTime.now();

            sales_date.setText(today.format(java.time.format.DateTimeFormatter.ofPattern("MMMM dd, yyyy")));
            sales_time.setText(now.format(java.time.format.DateTimeFormatter.ofPattern("hh:mm:ss a")));
            });
        timer.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sales_invtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        salestf_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        salestf_mfg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salestf_exp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salestf_price = new javax.swing.JTextField();
        salestf_qty = new javax.swing.JTextField();
        sales_add2chk = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sales_chktable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sales_time = new javax.swing.JLabel();
        sales_date = new javax.swing.JLabel();
        sales_back2inv = new javax.swing.JButton();
        sales_remv4chk = new javax.swing.JButton();
        sales_paycheck = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        salestf_total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        salestf_payment = new javax.swing.JTextField();
        salesbtn_chkout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eCommerce");
        setBackground(new java.awt.Color(0, 0, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sales Manager"));

        sales_invtable.setBackground(new java.awt.Color(255, 255, 204));
        sales_invtable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sales_invtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "DESCRIPTION", "MFG_DATE", "EXP_DATE", "PRICE", "QUANTITY", "SOLD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sales_invtable.setGridColor(new java.awt.Color(0, 0, 0));
        sales_invtable.setShowGrid(true);
        jScrollPane1.setViewportView(sales_invtable);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("NAME");

        salestf_name.setBackground(new java.awt.Color(255, 255, 204));
        salestf_name.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        salestf_name.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("MFG DATE");

        salestf_mfg.setBackground(new java.awt.Color(255, 255, 204));
        salestf_mfg.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        salestf_mfg.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("EXP DATE");

        salestf_exp.setBackground(new java.awt.Color(255, 255, 204));
        salestf_exp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        salestf_exp.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("PRICE");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("QUANTITY");

        salestf_price.setBackground(new java.awt.Color(255, 255, 204));
        salestf_price.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        salestf_price.setEnabled(false);

        salestf_qty.setBackground(new java.awt.Color(255, 255, 204));
        salestf_qty.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        sales_add2chk.setBackground(new java.awt.Color(0, 51, 0));
        sales_add2chk.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        sales_add2chk.setForeground(new java.awt.Color(255, 255, 204));
        sales_add2chk.setText("ADD TO CHECKOUT");
        sales_add2chk.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sales_add2chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_add2chkActionPerformed(evt);
            }
        });

        sales_chktable.setBackground(new java.awt.Color(255, 255, 204));
        sales_chktable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sales_chktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PRICE", "QUANTITY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sales_chktable.setGridColor(new java.awt.Color(0, 0, 0));
        sales_chktable.setShowGrid(false);
        sales_chktable.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(sales_chktable);
        if (sales_chktable.getColumnModel().getColumnCount() > 0) {
            sales_chktable.getColumnModel().getColumn(0).setResizable(false);
            sales_chktable.getColumnModel().getColumn(1).setResizable(false);
            sales_chktable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("CHECKOUT $$$");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setText("INVENTORY");

        sales_time.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        sales_time.setText("TIME 00:00:00");

        sales_date.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        sales_date.setText("DATE");

        sales_back2inv.setBackground(new java.awt.Color(51, 51, 51));
        sales_back2inv.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        sales_back2inv.setForeground(new java.awt.Color(255, 255, 0));
        sales_back2inv.setText("BACK TO INVENTORY");
        sales_back2inv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sales_back2inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_back2invActionPerformed(evt);
            }
        });

        sales_remv4chk.setBackground(new java.awt.Color(0, 51, 0));
        sales_remv4chk.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        sales_remv4chk.setForeground(new java.awt.Color(255, 51, 51));
        sales_remv4chk.setText("REMOVE FROM CHECKOUT");
        sales_remv4chk.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sales_remv4chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_remv4chkActionPerformed(evt);
            }
        });

        sales_paycheck.setBackground(new java.awt.Color(0, 51, 0));
        sales_paycheck.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        sales_paycheck.setForeground(new java.awt.Color(255, 255, 255));
        sales_paycheck.setText("CHECKOUT TOTAL");
        sales_paycheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_paycheckActionPerformed(evt);
            }
        });

        jLabel6.setText("TOTAL :");

        jLabel9.setText("CASH :");

        salesbtn_chkout.setBackground(new java.awt.Color(51, 102, 0));
        salesbtn_chkout.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        salesbtn_chkout.setForeground(new java.awt.Color(0, 204, 0));
        salesbtn_chkout.setText("PAY CHECKOUT $$$");
        salesbtn_chkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesbtn_chkoutActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 0));
        jButton1.setText("REFRESH INVENTORY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sales_add2chk, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sales_remv4chk))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sales_paycheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salesbtn_chkout, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sales_time)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sales_date)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(salestf_name)
                                    .addComponent(salestf_mfg)
                                    .addComponent(salestf_exp)
                                    .addComponent(salestf_price)
                                    .addComponent(salestf_qty))))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(sales_back2inv))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salestf_payment)
                            .addComponent(salestf_total))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, sales_add2chk, sales_back2inv, sales_paycheck, sales_remv4chk});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sales_back2inv)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sales_time)
                    .addComponent(sales_date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(salestf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(salestf_mfg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(salestf_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(salestf_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(salestf_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salesbtn_chkout, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sales_add2chk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sales_remv4chk))
                    .addComponent(sales_paycheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(salestf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(salestf_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, sales_back2inv});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sales_add2chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_add2chkActionPerformed
        try {
        
            boolean success = deductItemQuantityFromSelectedRow();
            FileHandler.saveToFile(RECORDS.RECORDS, "RECORDS.dat");
                System.out.println("DATA UPDATED.");
            if (!success) {
                return;
            }
            FileHandler.saveToFile(RECORDS.RECORDS, "RECORDS.dat");
                System.out.println("DATA UPDATED.");
        
            String NAME = salestf_name.getText().trim();
            double PRICE = Double.parseDouble(salestf_price.getText().trim());
            int QUANTITY = Integer.parseInt(salestf_qty.getText().trim());

            DefaultTableModel chkModel = (DefaultTableModel) sales_chktable.getModel();
        
            chkModel.addRow(new Object[]{NAME, PRICE, QUANTITY});

        
            salestf_name.setText("");
            salestf_price.setText("");
            salestf_qty.setText("");
            salestf_mfg.setText("");
            salestf_exp.setText("");
            FileHandler.saveToFile(RECORDS.RECORDS, "RECORDS.dat");
                System.out.println("DATA UPDATED.");

            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for price and quantity.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_sales_add2chkActionPerformed

    private void sales_remv4chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_remv4chkActionPerformed
        try {
        
        int chkRow = sales_chktable.getSelectedRow();
        if (chkRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item in the checkout table first.");
            return;
        }

        DefaultTableModel chkModel = (DefaultTableModel) sales_chktable.getModel();

        
        Object nameObj = chkModel.getValueAt(chkRow, 0);
        Object qtyObj  = chkModel.getValueAt(chkRow, 2);

        if (nameObj == null || qtyObj == null) {
            JOptionPane.showMessageDialog(this, "Selected checkout row has missing data.");
            return;
        }

        String name = nameObj.toString();
        int qtyToReturn;
        try {
            qtyToReturn = Integer.parseInt(qtyObj.toString());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Invalid quantity in checkout row.");
            return;
        }

        
        DefaultTableModel invModel = (DefaultTableModel) sales_invtable.getModel();
        int invRow = -1;
        for (int i = 0; i < invModel.getRowCount(); i++) {
            Object invNameObj = invModel.getValueAt(i, 0);
            if (invNameObj != null && name.equals(invNameObj.toString())) {
                invRow = i;
                break;
            }
        }

        if (invRow == -1) {
            JOptionPane.showMessageDialog(this, "Matching inventory item not found. Select the inventory item to update.");
            return;
        }

        
        int currentQty = 0;
        int currentSold = 0;
        Object curQtyObj = invModel.getValueAt(invRow, 5);
        Object curSoldObj = invModel.getValueAt(invRow, 6);

        if (curQtyObj != null) {
            try { currentQty = Integer.parseInt(curQtyObj.toString()); } catch (NumberFormatException ignored) {}
        }
        if (curSoldObj != null) {
            try { currentSold = Integer.parseInt(curSoldObj.toString()); } catch (NumberFormatException ignored) {}
        }

        
        int newQty = currentQty + qtyToReturn;
        int newSold = currentSold + qtyToReturn;

        invModel.setValueAt(newQty, invRow, 5);
        invModel.setValueAt(newSold, invRow, 6);

       
        boolean updatedRecord = false;
        if (RECORDS.RECORDS != null) {
            for (RECORDS r : RECORDS.RECORDS) {
                if (r.getNAME() != null && r.getNAME().equals(name)) {
                    try {
                        r.setQUANTITY(newQty);
                        r.setSOLD(newSold);
                        updatedRecord = true;
                    } catch (Exception ex) {
                        
                        System.out.println("Could not set fields on RECORDS object: " + ex.getMessage());
                    }
                    break;
                }
            }
        }

        
        try {
            FileHandler.saveToFile(RECORDS.RECORDS, "Records.dat");
        } catch (Exception ex) {
            System.out.println("Warning: could not save Records.dat: " + ex.getMessage());
        }

       
        if (SALESinv.SALESinvRECORDS != null && !SALESinv.SALESinvRECORDS.isEmpty()) {
            int removeIndex = -1;
            for (int i = 0; i < SALESinv.SALESinvRECORDS.size(); i++) {
                SALESinv s = SALESinv.SALESinvRECORDS.get(i);
                if (s.getNAME() != null && s.getNAME().equals(name)) {
                    removeIndex = i;
                    break;
                }
            }
            if (removeIndex != -1 && removeIndex < SALESinv.SALESinvRECORDS.size()) {
                SALESinv.SALESinvRECORDS.remove(removeIndex);
            }
        }

        chkModel.removeRow(chkRow);

        loadRecordsToTable();

        salestf_qty.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage());
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_sales_remv4chkActionPerformed

    private void sales_back2invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_back2invActionPerformed
        manager m = new manager();
    m.setLocationRelativeTo(null);
    m.setVisible(true);
    SALESFILEHANDLER.saveToFile(SALESinv.SALESinvRECORDS, "SALESinvRECORDS.dat");
    loadRecordsToTable();
    this.dispose(); 
    }//GEN-LAST:event_sales_back2invActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadRecordsToTable();
        javax.swing.JOptionPane.showMessageDialog(this, "Data loaded succesfully!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadRecordsToTable();
    }//GEN-LAST:event_formWindowActivated

    private void sales_paycheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_paycheckActionPerformed
        double total = 0.0;
    DefaultTableModel model = (DefaultTableModel) sales_chktable.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        try {
            
            double price = Double.parseDouble(model.getValueAt(i, 1).toString());
            int qty = Integer.parseInt(model.getValueAt(i, 2).toString());

            total += price * qty;
            
            SALESFILEHANDLER.saveToFile(SALESinv.SALESinvRECORDS, "SALESinvRECORDS.dat");
        } catch (Exception e) {
            System.out.println("Error at row " + i + ": " + e.getMessage());
        }
    }

    salestf_total.setText(String.format("%.2f", total));
    }//GEN-LAST:event_sales_paycheckActionPerformed

    private void salesbtn_chkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesbtn_chkoutActionPerformed
            try {
                double total = Double.parseDouble(salestf_total.getText());
                double payment = Double.parseDouble(salestf_payment.getText());
                double change = payment - total;
                SALESFILEHANDLER.saveToFile(SALESinv.SALESinvRECORDS, "SALESinvRECORDS.dat");

                CHECKOUT checkoutFrame = new CHECKOUT();

                DefaultTableModel salesModel = (DefaultTableModel) sales_chktable.getModel();
                checkoutFrame.setCheckoutData(salesModel);
                checkoutFrame.chk_change.setText(String.format("%.2f", change));
                checkoutFrame.chktf_PRICE.setText(String.format("%.2f", total));
                checkoutFrame.setLocationRelativeTo(null);
                checkoutFrame.setVisible(true);

                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, 
                        "Please enter valid numbers for Total and Payment.", 
                        "Input Error", 
                        JOptionPane.ERROR_MESSAGE);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, 
                            "An unexpected error occurred: " + e.getMessage());
                            e.printStackTrace();
                        }
    
    
    }//GEN-LAST:event_salesbtn_chkoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SALES().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sales_add2chk;
    private javax.swing.JButton sales_back2inv;
    private javax.swing.JTable sales_chktable;
    private javax.swing.JLabel sales_date;
    private javax.swing.JTable sales_invtable;
    private javax.swing.JButton sales_paycheck;
    private javax.swing.JButton sales_remv4chk;
    private javax.swing.JLabel sales_time;
    private javax.swing.JButton salesbtn_chkout;
    private javax.swing.JTextField salestf_exp;
    private javax.swing.JTextField salestf_mfg;
    private javax.swing.JTextField salestf_name;
    private javax.swing.JTextField salestf_payment;
    private javax.swing.JTextField salestf_price;
    private javax.swing.JTextField salestf_qty;
    private javax.swing.JTextField salestf_total;
    // End of variables declaration//GEN-END:variables

    private void loadSALESRecordsToTable() {
       try {

        SALESinv.SALESinvRECORDS = SALESFILEHANDLER.loadFromFile("SALESinvRECORDS.dat");

        DefaultTableModel model = (DefaultTableModel) sales_chktable.getModel();
        model.setRowCount(0);

        for (SALESinv r : SALESinv.SALESinvRECORDS) {
            model.addRow(new Object[]{
                r.getNAME(),
                r.getQUANTITY(),
                r.getPRICE(),
                r.getSOLD(),
            });
        }

        System.out.println("Records loaded successfully from Records.dat");

        } catch (Exception e) {
        System.out.println("Error loading records: " + e.getMessage());
        }
     
        
    }
    
    
    private void loadRecordsToTable() {
       try {

        RECORDS.RECORDS = FileHandler.loadFromFile("Records.dat");

        DefaultTableModel model = (DefaultTableModel) sales_invtable.getModel();
        model.setRowCount(0);

        for (RECORDS r : RECORDS.RECORDS) {
            model.addRow(new Object[]{
                r.getNAME(),
                r.getINFO(),
                r.getMFG_DATE(),
                r.getEXP_DATE(),
                r.getPRICE(),
                r.getQUANTITY()
            });
        }

        System.out.println("Records loaded successfully from Records.dat");

        } catch (Exception e) {
        System.out.println("Error loading records: " + e.getMessage());
        }
     
        
    }
    private boolean deductItemQuantityFromSelectedRow() {
    try {
        DefaultTableModel invModel = (DefaultTableModel) sales_invtable.getModel();
        int selectedRow = sales_invtable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an item from the inventory table first.");
            return false;
        }
        String qtyText = salestf_qty.getText().trim();
        if (qtyText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a quantity to sell.");
            return false;
        }

        int inputQty;
        try {
            inputQty = Integer.parseInt(qtyText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Quantity must be an integer.");
            return false;
        }

        if (inputQty <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.");
            return false;
        }

        Object qtyObj = invModel.getValueAt(selectedRow, 5);
        if (qtyObj == null) {
            JOptionPane.showMessageDialog(this, "Selected inventory row has no quantity value.");
            return false;
        }

        int currentQty;
        try {
            currentQty = Integer.parseInt(qtyObj.toString());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Current inventory quantity is not a valid number.");
            return false;
        }

        if (inputQty > currentQty) {
            JOptionPane.showMessageDialog(this, "Not enough stock available!");
            return false;
        }

        int newQty = currentQty - inputQty;
        invModel.setValueAt(newQty, selectedRow, 5);
        
        if (selectedRow < RECORDS.RECORDS.size()) {
        RECORDS item = RECORDS.RECORDS.get(selectedRow);
        item.setQUANTITY(newQty);
        }
        
        FileHandler.saveToFile(RECORDS.RECORDS, "Records.dat");

        
        return true;

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating inventory: " + e.getMessage());
        e.printStackTrace();
        return false;
    }
}
}
